In [1]:
import numpy as np

In [2]:
arr = np.array([23,45,67,89,10])

In [3]:
print(arr)

[23 45 67 89 10]


In [4]:
arr

array([23, 45, 67, 89, 10])

In [5]:
type(arr)

numpy.ndarray

In [6]:
arr[2]

67

In [7]:
arr[2]=100

In [8]:
arr

array([ 23,  45, 100,  89,  10])

In [9]:
arr[1]=100

In [10]:
arr

array([ 23, 100, 100,  89,  10])

In [11]:
arr1 = np.array([12,34.98,55,True,"Pune"])

In [12]:
arr1

array(['12', '34.98', '55', 'True', 'Pune'], dtype='<U32')

In [13]:
arr1.dtype

dtype('<U32')

##### Check which one is faster ......list or array

In [14]:
import time

In [15]:
time.time()

1753018237.783094

In [16]:
s = 100000

list1 = list(range(s))
arr1 = np.array(list1)

In [17]:
arr1

array([    0,     1,     2, ..., 99997, 99998, 99999])

##### for list

In [18]:
start_time = time.time()
a = [i * 2 for i in arr1]
time_arr = time.time() - start_time
print("time taken by array:",time_arr)

time taken by array: 0.04095888137817383


#### For array

In [19]:
start_time = time.time()
y = arr1 * 2
time_list = time.time() - start_time
print("time taken by list:",time_list)

time taken by list: 0.008001327514648438


In [20]:
time_list / time_arr

0.1953502450609451

##### arange 

In [21]:
a = np.arange(11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
np.arange(5,15)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
np.arange(-5,5,0.5)

array([-5. , -4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,
        0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [24]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [25]:
arr

array([ 23, 100, 100,  89,  10])

In [26]:
arr.ndim

1

##### 2-D Array

In [27]:
arr = np.array([[1,2,3],[4,2,5],[6,9,4],[6,3,8]])

In [28]:
arr

array([[1, 2, 3],
       [4, 2, 5],
       [6, 9, 4],
       [6, 3, 8]])

In [29]:
arr.ndim

2

In [30]:
arr.size

12

In [31]:
arr.shape

(4, 3)

In [32]:
arr.flatten()

array([1, 2, 3, 4, 2, 5, 6, 9, 4, 6, 3, 8])

In [33]:
arr.flatten().ndim

1

In [34]:
arr

array([[1, 2, 3],
       [4, 2, 5],
       [6, 9, 4],
       [6, 3, 8]])

In [35]:
arr.reshape(6,2)

array([[1, 2],
       [3, 4],
       [2, 5],
       [6, 9],
       [4, 6],
       [3, 8]])

In [36]:
arr.reshape(2,6)

array([[1, 2, 3, 4, 2, 5],
       [6, 9, 4, 6, 3, 8]])

In [37]:
arr.reshape(2, -1)

array([[1, 2, 3, 4, 2, 5],
       [6, 9, 4, 6, 3, 8]])

In [38]:
arr.reshape(3,2,2)

array([[[1, 2],
        [3, 4]],

       [[2, 5],
        [6, 9]],

       [[4, 6],
        [3, 8]]])

##### Slicing

In [39]:
arr

array([[1, 2, 3],
       [4, 2, 5],
       [6, 9, 4],
       [6, 3, 8]])

In [40]:
arr1 = np.arange(3,13)

In [41]:
arr1

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [42]:
arr1[3:7]

array([6, 7, 8, 9])

In [43]:
arr[1:3,0:2]

array([[4, 2],
       [6, 9]])

In [44]:
arr[1:3, 0:3]

array([[4, 2, 5],
       [6, 9, 4]])

In [45]:
arr1

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [46]:
np.mean(arr1)

7.5

In [47]:
np.std(arr1)

2.8722813232690143

In [48]:
a = np.array([[1,4],[4,9]])
b = np.array([[3,3],[10,1]])

In [49]:
a

array([[1, 4],
       [4, 9]])

In [50]:
b

array([[ 3,  3],
       [10,  1]])

In [51]:
a @ b

array([[ 43,   7],
       [102,  21]])

In [52]:
np.dot(a,b)

array([[ 43,   7],
       [102,  21]])

In [53]:
np.linalg.det(a)

-6.999999999999999

In [54]:
np.linalg.inv(a)

array([[-1.28571429,  0.57142857],
       [ 0.57142857, -0.14285714]])

In [55]:
np.linalg.eig(a)

EigResult(eigenvalues=array([-0.65685425, 10.65685425]), eigenvectors=array([[-0.92387953, -0.38268343],
       [ 0.38268343, -0.92387953]]))

##### Vector

In [56]:
vec = np.array([3,6])

In [57]:
np.linalg.norm(vec)

6.708203932499369

In [58]:
help(np.linalg.norm)

Help on _ArrayFunctionDispatcher in module numpy.linalg:

norm(x, ord=None, axis=None, keepdims=False)
    Matrix or vector norm.

    This function is able to return one of eight different matrix norms,
    or one of an infinite number of vector norms (described below), depending
    on the value of the ``ord`` parameter.

    Parameters
    ----------
    x : array_like
        Input array.  If `axis` is None, `x` must be 1-D or 2-D, unless `ord`
        is None. If both `axis` and `ord` are None, the 2-norm of
        ``x.ravel`` will be returned.
    ord : {non-zero int, inf, -inf, 'fro', 'nuc'}, optional
        Order of the norm (see table under ``Notes``). inf means numpy's
        `inf` object. The default is None.
    axis : {None, int, 2-tuple of ints}, optional.
        If `axis` is an integer, it specifies the axis of `x` along which to
        compute the vector norms.  If `axis` is a 2-tuple, it specifies the
        axes that hold 2-D matrices, and the matrix norms of th

##### QUESTION

In [59]:
##1 create a Numpy of shape(3,3) with values ranging from (0 to 9)
a = np.arange(1,10)
a.reshape(3,3)


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
##2 Given a 1D array[10,20,30,40,50] , write code to reverse the array

arr = [10,20,30,40,50]
rev_arr = arr[::-1]
print(rev_arr)

[50, 40, 30, 20, 10]


In [61]:
##3 Create a 5x5 Numpy array filled with zeros and set the value of the middle element 1

import numpy as np
a = np.zeros((5,5), dtype=int)
a[2,2] =1
print(a)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 1 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [62]:
##4 Generate a Numpy array with 20 random integers between 1 to 100. Replace all even numbers with -1

random_array = np.random.randint(1, 101, size=20)
random_array[random_array % 2 == 0] = -1

print(random_array)

[-1 53 -1 55 -1  5 -1 -1 11 11 -1 -1 -1 -1 -1 -1 59 55 -1 39]


In [65]:
###5 Given a NumPy array a = np.array([[1, 2], [3, 4], [5, 6]]) , extract the second column

import numpy as np 
sec = np.array([[1, 2], [3, 4], [5, 6]])
second_col = sec[:, 1]

print(second_col)

[2 4 6]


In [66]:
###6 Create a NumPy array with values [1, 2, 3, 4] and convert it into a 2x2 matrix

arr = np.array([1, 2, 3, 4])
matrix = arr.reshape(2, 2)
print("2x2 Matrix:\n", matrix)


2x2 Matrix:
 [[1 2]
 [3 4]]


In [67]:
###7 Create two NumPy arrays of shape (2, 2) and perform element-wise addition, subtraction,multiplication, and division.

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

add = a + b
sub = a - b
mul = a * b
div = a / b

print("Addition:\n", add)
print("---------------------")
print("Subtraction:\n", sub)
print("---------------------")
print("Multiplication:\n", mul)
print("---------------------")
print("Division:\n", div)


Addition:
 [[ 6  8]
 [10 12]]
---------------------
Subtraction:
 [[-4 -4]
 [-4 -4]]
---------------------
Multiplication:
 [[ 5 12]
 [21 32]]
---------------------
Division:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [68]:
###8 Use NumPy to create an array of 10 linearly spaced values between 0 and 1.

linear_values = np.linspace(0, 1, 10)
print("Linearly spaced values:\n", linear_values)

Linearly spaced values:
 [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [69]:
###9 Create a NumPy array and demonstrate how to compute its mean, median, and standard deviation.

help(np.mean)

Help on _ArrayFunctionDispatcher in module numpy:

mean(a, axis=None, dtype=None, out=None, keepdims=<no value>, *, where=<no value>)
    Compute the arithmetic mean along the specified axis.

    Returns the average of the array elements.  The average is taken over
    the flattened array by default, otherwise over the specified axis.
    `float64` intermediate and return values are used for integer inputs.

    Parameters
    ----------
    a : array_like
        Array containing numbers whose mean is desired. If `a` is not an
        array, a conversion is attempted.
    axis : None or int or tuple of ints, optional
        Axis or axes along which the means are computed. The default is to
        compute the mean of the flattened array.

        .. versionadded:: 1.7.0

        If this is a tuple of ints, a mean is performed over multiple axes,
        instead of a single axis or all the axes as before.
    dtype : data-type, optional
        Type to use in computing the mean.  For

In [70]:
help(np.median)

Help on _ArrayFunctionDispatcher in module numpy:

median(a, axis=None, out=None, overwrite_input=False, keepdims=False)
    Compute the median along the specified axis.

    Returns the median of the array elements.

    Parameters
    ----------
    a : array_like
        Input array or object that can be converted to an array.
    axis : {int, sequence of int, None}, optional
        Axis or axes along which the medians are computed. The default
        is to compute the median along a flattened version of the array.
        A sequence of axes is supported since version 1.9.0.
    out : ndarray, optional
        Alternative output array in which to place the result. It must
        have the same shape and buffer length as the expected output,
        but the type (of the output) will be cast if necessary.
    overwrite_input : bool, optional
       If True, then allow use of memory of input array `a` for
       calculations. The input array will be modified by the call to
       `me

In [71]:
data = np.array([10, 20, 30, 40, 50])

mean_val = np.mean(data)
median_val = np.median(data)
std_dev = np.std(data)

print("Mean:", mean_val)
print("Median:", median_val)
print("Standard Deviation:", std_dev)


Mean: 30.0
Median: 30.0
Standard Deviation: 14.142135623730951


In [72]:
###10 Given a 2D NumPy array, write a function to normalize each column (subtract mean and divide by std deviation).

def normalize_col(arr):
    mean = np.mean(arr, axis=0)
    std = np.std(arr, axis=0)
    std[std == 0] = 1
    return (arr - mean) / std

data = np.array([[1, 2], [3, 4], [5, 6]])
normalized = normalize_col(data)
print("Normalized array:\n", normalized)

Normalized array:
 [[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]
